name = "voicedot-platform"
main = "src/index.ts"
compatibility_date = "2024-01-01"
[env.production]
name = "voicedot-platform"
[[d1_databases]]
binding = "DB"
database_name = "voicedot-db"
database_id = "your-database-id"
[[r2_buckets]]
binding = "R2"
bucket_name = "voicedot-storage"
[vars]
NODE_ENV = "production"
